service phantom
{
    disable     = no
    type        = UNLISTED
    socket_type = stream
    protocol    = tcp
    port        = 30207
    wait        = no
    user        = ctf
    server      = /home/phantom
    log_type    = SYSLOG daemon info
    log_on_success  = HOST PID
    log_on_failure  = HOST
    instances = 20
    per_source  = 3
    rlimit_cpu  = 30
    rlimit_as   = 64M
}
